Repository TBD54566975/incubation-dcx, pull requests merged in 2024-10, with the labels that each got.

#145 Well known
  .well-known/credential/EmailCredential
  .well-known/credential/HandshakeCredential
  .well-known/credential/PhoneCredential
  .well-known/did
  .well-known/did.json
  .well-known/manifest/email
  .well-known/manifest/handshake
  .well-known/manifest/phone
  .well-known/protocol/applicant
  .well-known/protocol/dcx
  .well-known/protocol/issuer
  .well-known/protocol/mfa
  .well-known/schema/application
  .well-known/schema/invoice
  .well-known/schema/manifest
  .well-known/schema/mfa
  .well-known/schema/response
Labels: documentation

#146 Al add devcontainer env
  .devcontainer/applicant-service/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/images/Dockerfile.node
  .devcontainer/issuer-service/devcontainer.json
  .devcontainer/scripts/node/.envrc
  .devcontainer/scripts/node/install_global_npm_deps.sh
  .devcontainer/scripts/shared/common_debian.sh
  .devcontainer/scripts/shared/run.sh
  .devcontainer/server-package/devcontainer.json
  .gitignore
  docker-compose.yml
  docs/LOCAL_DEVELOPMENT.md
  justfile
Labels: hacktoberfest 2024, hacktoberfest, hacktoberfest-accepted, medium

#144 feat: github action for creating releases
  .github/workflows/release.yml
Labels: hacktoberfest, hacktoberfest-accepted, medium
